steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-django-app", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/my-django-app"]

images:
  - "gcr.io/$PROJECT_ID/my-django-app"

options:
  logging: "CLOUD_LOGGING_ONLY"
